# This is a basic workflow to help you get started with Actions

name: loc

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Download cloc
        run: sudo apt-get update -y && sudo apt-get install -y cloc
      - name: Get the Numbers
        run: |
          echo "CODE_LINES=$(cloc main.cpp src/* include/* | grep SUM: | grep -Eo '[0-9]+$')" >> $GITHUB_ENV
      - name: Dynamic Badges
        uses: Schneegans/dynamic-badges-action@v1.0.0
        with:
          # Your secret with the gist scope
          auth: ${{ secrets.GIST_SECRET }}
          # The ID of the gist to use
          gistID: 0dcf4bcb56b05761ea94e6abaf6ee405
          # The *.json filename of the badge data
          filename: RQEngineLOC.json
          # The left text of the badge
          label: lines
          # The right text of the badge
          message: ${{ env.CODE_LINES }}
          # The right color of the badge
          color: blue # optional
